### ISSUE TITLE
Unable to install in windows with latest version TDMtermite

### ISSUE THREAD

**Issue by srinivasseema** [RecordEvolution/TDMtermite#10]
Hi, Thanks for solving earlier windows issue.
I am unable to install latest version with below errors:

Collecting TDMtermite
  Using cached TDMtermite-1.0.1.tar.gz (132 kB)
Building wheels for collected packages: TDMtermite
  Building wheel for TDMtermite (setup.py): started
  Building wheel for TDMtermite (setup.py): finished with status 'error'
  Running setup.py clean for TDMtermite
Failed to build TDMtermite
Installing collected packages: TDMtermite
    Running setup.py install for TDMtermite: started
    Running setup.py install for TDMtermite: finished with status 'error'

  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\winuser\PycharmProjects\TDMParser\venv\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\winuser\\AppData\\Local\\Temp\\pip-install-8mguylts\\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\\setup.py'"'"'; __file__='"'"'C:\\Users\\winuser\\AppData\\Local\\Temp\\pip-install-8mguylts\\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\winuser\AppData\Local\Temp\pip-wheel-1w_wk0nq'
       cwd: C:\Users\winuser\AppData\Local\Temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\
  Complete output (54 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'tdm_termite' extension
  creating build
  creating build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\Release
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\winuser\PycharmProjects\TDMParser\venv\include -IC:\Users\winuser\AppData\Local\Programs\Python\Python39\include -IC:\Users\winuser\AppData\Local\Programs\Python\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt /EHsc /Tppy_tdm_termite.cpp /Fobuild\temp.win-amd64-3.9\Release\py_tdm_termite.obj -std=c++17
  cl : Command line warning D9002 : ignoring unknown option '-std=c++17'
  py_tdm_termite.cpp
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(97): error C2039: 'filesystem': is not a member of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(97): error C3083: 'filesystem': the symbol to the left of a '::' must be a type
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(97): error C2039: 'path': is not a member of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(97): error C2065: 'path': undeclared identifier
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(97): error C2146: syntax error: missing ';' before identifier 'ptdm'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(97): error C3861: 'ptdm': identifier not found
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(97): error C3861: 'ptdx': identifier not found
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(98): error C2039: 'filesystem': is not a member of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(98): error C3083: 'filesystem': the symbol to the left of a '::' must be a type
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(98): error C2039: 'exists': is not a member of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(98): error C2065: 'ptdm': undeclared identifier
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(98): error C3861: 'exists': identifier not found
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(102): error C2039: 'filesystem': is not a member of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(102): error C3083: 'filesystem': the symbol to the left of a '::' must be a type
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(102): error C2039: 'exists': is not a member of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(102): error C2065: 'ptdx': undeclared identifier
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(102): error C3861: 'exists': identifier not found
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(855): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(913): error C2039: 'filesystem': is not a member of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(913): error C3083: 'filesystem': the symbol to the left of a '::' must be a type
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(913): error C2039: 'path': is not a member of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(913): error C2065: 'path': undeclared identifier
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(913): error C2146: syntax error: missing ';' before identifier 'pt'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(913): error C3861: 'pt': identifier not found
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(916): error C2065: 'pt': undeclared identifier
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(918): error C2039: 'filesystem': is not a member of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(918): error C3083: 'filesystem': the symbol to the left of a '::' must be a type
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(918): error C2039: 'is_directory': is not a member of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(918): error C2065: 'pt': undeclared identifier
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(918): error C3861: 'is_directory': identifier not found
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(920): error C2065: 'pt': undeclared identifier
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(920): error C2512: 'std::runtime_error': no appropriate default constructor available
  c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(920): note: No constructor could take the source type, or constructor overload resolution was ambiguous
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for TDMtermite
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\winuser\PycharmProjects\TDMParser\venv\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\winuser\\AppData\\Local\\Temp\\pip-install-8mguylts\\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\\setup.py'"'"'; __file__='"'"'C:\\Users\\winuser\\AppData\\Local\\Temp\\pip-install-8mguylts\\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\winuser\AppData\Local\Temp\pip-record-lepzagna\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\winuser\PycharmProjects\TDMParser\venv\include\site\python3.9\TDMtermite'
         cwd: C:\Users\winuser\AppData\Local\Temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\
    Complete output (54 lines):
    running install
    running build
    running build_ext
    building 'tdm_termite' extension
    creating build
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\winuser\PycharmProjects\TDMParser\venv\include -IC:\Users\winuser\AppData\Local\Programs\Python\Python39\include -IC:\Users\winuser\AppData\Local\Programs\Python\Python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt /EHsc /Tppy_tdm_termite.cpp /Fobuild\temp.win-amd64-3.9\Release\py_tdm_termite.obj -std=c++17
    cl : Command line warning D9002 : ignoring unknown option '-std=c++17'
    py_tdm_termite.cpp
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(97): error C2039: 'filesystem': is not a member of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(97): error C3083: 'filesystem': the symbol to the left of a '::' must be a type
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(97): error C2039: 'path': is not a member of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(97): error C2065: 'path': undeclared identifier
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(97): error C2146: syntax error: missing ';' before identifier 'ptdm'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(97): error C3861: 'ptdm': identifier not found
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(97): error C3861: 'ptdx': identifier not found
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(98): error C2039: 'filesystem': is not a member of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(98): error C3083: 'filesystem': the symbol to the left of a '::' must be a type
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(98): error C2039: 'exists': is not a member of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(98): error C2065: 'ptdm': undeclared identifier
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(98): error C3861: 'exists': identifier not found
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(102): error C2039: 'filesystem': is not a member of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(102): error C3083: 'filesystem': the symbol to the left of a '::' must be a type
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(102): error C2039: 'exists': is not a member of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(102): error C2065: 'ptdx': undeclared identifier
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(102): error C3861: 'exists': identifier not found
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(855): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(913): error C2039: 'filesystem': is not a member of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(913): error C3083: 'filesystem': the symbol to the left of a '::' must be a type
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(913): error C2039: 'path': is not a member of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(913): error C2065: 'path': undeclared identifier
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(913): error C2146: syntax error: missing ';' before identifier 'pt'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(913): error C3861: 'pt': identifier not found
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(916): error C2065: 'pt': undeclared identifier
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(918): error C2039: 'filesystem': is not a member of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(918): error C3083: 'filesystem': the symbol to the left of a '::' must be a type
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(918): error C2039: 'is_directory': is not a member of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\pugixml.cpp(7260): note: see declaration of 'std'
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(918): error C2065: 'pt': undeclared identifier
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(918): error C3861: 'is_directory': identifier not found
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(920): error C2065: 'pt': undeclared identifier
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(920): error C2512: 'std::runtime_error': no appropriate default constructor available
    c:\users\winuser\appdata\local\temp\pip-install-8mguylts\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\tdm_termite.cpp(920): note: No constructor could take the source type, or constructor overload resolution was ambiguous
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\winuser\PycharmProjects\TDMParser\venv\Scripts\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\winuser\\AppData\\Local\\Temp\\pip-install-8mguylts\\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\\setup.py'"'"'; __file__='"'"'C:\\Users\\winuser\\AppData\\Local\\Temp\\pip-install-8mguylts\\tdmtermite_2d4c66766b8841eaae75fcb2f4650801\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\winuser\AppData\Local\Temp\pip-record-lepzagna\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\winuser\PycharmProjects\TDMParser\venv\include\site\python3.9\TDMtermite' Check the logs for full command output.

**Comment by mario-fink** [comment]
please refer to version 1.0.2 and issue #9

**Comment by srinivasseema** [comment]
Thank you for the quick fix. Its getting installed now.

**Comment by mario-fink** [comment]
Thanks for you feedback. I'll consider the issue as resolved....
