### ISSUE TITLE
TDMtermite with alpine docker image

### ISSUE THREAD

**Issue by srinivasseema** [RecordEvolution/TDMtermite#11]
Hi, 

I am trying to install TDMtermite with jdk base image and its getting failed with below error:
Also, I would like to know if  any other available docker images with TDMtermite support.

Step 1/8 : FROM adoptopenjdk/openjdk11:jre-11.0.11_9-alpine
 ---> 98d92815b3d8
Step 2/8 : RUN apk add --no-cache python3 py3-pip
 ---> Using cache
 ---> f1356a0cedda
Step 3/8 : RUN pip install TDMtermite==1.0.2
 ---> Running in af855f8fd730
Collecting TDMtermite==1.0.2
  Downloading TDMtermite-1.0.2.tar.gz (132 kB)
Using legacy 'setup.py install' for TDMtermite, since package 'wheel' is not installed.
Installing collected packages: TDMtermite
    Running setup.py install for TDMtermite: started
    Running setup.py install for TDMtermite: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i77gxr8b/tdmtermite_d705b1bcd18a45c5a5ff930447681775/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i77gxr8b/tdmtermite_d705b1bcd18a45c5a5ff930447681775/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zvo28vui/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/TDMtermite
         cwd: /tmp/pip-install-i77gxr8b/tdmtermite_d705b1bcd18a45c5a5ff930447681775/
    Complete output (10 lines):
    building on platform: linux
    running install
    running build
    running build_ext
    building 'tdm_termite' extension
    creating build
    creating build/temp.linux-x86_64-3.8
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -I/usr/include/python3.8 -c py_tdm_termite.cpp -o build/temp.linux-x86_64-3.8/py_tdm_termite.o -std=c++17 -Wno-unused-variable
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-i77gxr8b/tdmtermite_d705b1bcd18a45c5a5ff930447681775/setup.py'"'"'; __file__='"'"'/tmp/pip-install-i77gxr8b/tdmtermite_d705b1bcd18a45c5a5ff930447681775/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zvo28vui/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.8/TDMtermite Check the logs for full command output.
Error response from daemon: The command '/bin/sh -c pip install TDMtermite==1.0.2' returned a non-zero code: 1
Failed to deploy '<unknown> Dockerfile: Dockerfile': Can't retrieve image ID from build stream

Thank you..

**Comment by mario-fink** [comment]
It seems like your alpine base image does not feature `gcc` by default, so include it by
`RUN apk add build-base`.
You will also need some python/cython development headers/libraries provided by 
`RUN apk add python3-dev`.
So in summary, something like 
```
FROM adoptopenjdk/openjdk11:jre-11.0.11_9-alpine

RUN apk add --no-cache python3 py3-pip

RUN apk add build-base 
#&& python3 -m pip install cython
RUN apk add python3-dev

RUN pip install TDMtermite==1.0.2

CMD ["sleep","3600"]
```
should do....

**Comment by srinivasseema** [comment]
Thank you for your quick response and support!
