### ISSUE TITLE
datatype: DT_STRING is unknown/invalid

### ISSUE THREAD

**Issue by adamjnicholls** [RecordEvolution/TDMtermite#15]
Hi,
v1.0.4 reading a .tdm file (afraid I can't share it as it's confidential) I get the error "datatype: DT_STRING is unknown/invalid"

I'm surprised it's not valid as it's generated by DIAdem?
I tried doing find/replace on DT_STRING in the .tdm / xml file with just STRING but the same error appeared. Presumably the .tdx file has it in as well but in the binary but I'm not so clear on the format...

**Comment by mario-fink** [comment]
I added/activated experimental support for the DT_STRING datatype. As of version 1.0.5 this data will be simply put out as its corresponding numerical codepoint. Please let me know what a more reasonable representation could look like! 
ef16fd322817db3e64ef1d88281a2f2b7c029ed3
