### ISSUE TITLE
Unable to compile for Windows ?

### ISSUE THREAD

**Issue by nervalo88** [RecordEvolution/TDMtermite#9]
Hello,

under windows, wheel compilation leads to the error below.
I used anaconda python 3.8.8 64bit dist, and also tried python 3.9.

Visual studio build tools installed also, without success.

[Consoleoutput.txt](https://github.com/RecordEvolution/TDMtermite/files/6610289/Consoleoutput.txt)

found a workaround using WSL, which works pretty well, but is not suitable for the complete project. 
I'm unfortunately a complete beginner with python packages and can provide only some extra test results.

thanks for your help !

**Comment by mario-fink** [comment]
Thanks for your issue! I'll have a look into it a.s.a.p...

**Comment by mario-fink** [comment]
Please try again to install the pip package with version latest version 1.0.2 . It least for me it now works on Windows10 with MSVC 14.16.27023. Please feel free to reopen the issue if the problem persists.
